/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package org.lstsyntaxhighlighting.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int whitespace = 1;
  /** RegularExpression Id. */
  int comment = 2;
  /** RegularExpression Id. */
  int number = 3;
  /** RegularExpression Id. */
  int identifier = 4;
  /** RegularExpression Id. */
  int separator = 5;
  /** RegularExpression Id. */
  int keyword = 6;
  /** RegularExpression Id. */
  int operator = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<whitespace>",
    "<comment>",
    "<number>",
    "<identifier>",
    "<separator>",
    "<keyword>",
    "<operator>",
  };

}
